version: '3'

services:
  certbot:
    container_name: certbot
    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
      - DOMAIN_EMAIL=${DOMAIN_EMAIL}

    image: certbot/certbot
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email ${DOMAIN_EMAIL} --agree-tos --non-interactive -d ${DOMAIN}
    depends_on:
      - nginx

  certbot-renewer:
    container_name: certbot-renewer
    image: certbot/certbot
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
    command: renew --webroot --webroot-path=/var/www/html --non-interactive
    depends_on:
      - nginx
