version: '3'

services:
  nginx:

    image: nginx
    container_name: nginx

    depends_on:
      - web

    ports:
      - "80:80"
      - "443:443"

    env_file: .env

    # environment:
    #   - DOMAIN=${DOMAIN}
    #   - DOMAIN_PORT=${DOMAIN_PORT}
    
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    volumes:
      - ./forge/app/nginx.stage.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/nginx/certs/privkey.pem

