version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"

    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
      - DOMAIN_PORT=${DOMAIN_PORT}
    
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    volumes:
      - ./forge/app/nginx.stage.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt

#     - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/nginx/certs/fullchain.pem
#     - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/nginx/certs/privkey.pem
